### ISSUE TITLE
Feature Request - Show Signal values through web

### ISSUE THREAD

**Issue by 3xtr3m3d** [Dima73/enigma2-plugin-signalfinder#3]
Hi, Sorry if i open this in wrong section. 

it will be very valuable if we can see SNR, AGC, BER values through a web interface. so we can use it as a true signal finder when dish is located far away from the screen.

i managed to start a simple webserver on a port when this plugin is launched but i have no idea how to read these values from plugin

please add this feature if you can

Regards

**Comment by Dima73** [comment]
Use OpenWebif or other applications for android ,e.g. Enigma Signal Meter-SatFinder.
https://play.google.com/store/apps/details?id=com.krkadoni.app.signalmeter&hl=ru

**Comment by 3xtr3m3d** [comment]
those doesnt show values when using signalfinder plugin.  it shows values of active transponder when watching TV only. so those apps useless :(

**Comment by moham96** [comment]
@Dima73 I really love this plugin and really need a webif extension for it.
As @3xtr3m3d said, all these apps show the info provided by the [web/signal](https://dream.reichholf.net/e2web/#signal) API which needs a channel to tune into, this is useless when setting up a new satellite and your channel list is empty, this is where signalfinder plugin comes into play where you can select any transponder and show it's signal levels.
This should have it's own webif extension so you can use it remotely.

Regards

**Comment by moham96** [comment]
I think the plugin should implement two things:
- a JSON API that provides the info(SNR,AGC...etc) and also support requests(change the TP and other settings), this api can be used by mobile apps and the web interface.
https://github.com/OpenDMM/enigma2/blob/b5f18e208b81cad61723586c061fa5abb305a7d6/usr/lib/enigma2/python/Plugins/SystemPlugins/JSONApi/plugin.py

- a web interface that uses the JSON API.
 Similar to these:
https://github.com/OpenPLi/enigma2-plugins/blob/53ab59ef496ea74180266c323f8190c35bb499a2/fancontrol2/src/plugin.py#L1241-L1271
https://github.com/PLi-metas/iptvplayer-for-e2/blob/master/IPTVPlayer/Web/initiator.py

I'm pretty new to the enigma2 platform, so I don't know much about plugins and have to read more about it, hoping @Dima73  can solve this.

Regards
